In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

sets of brakets tell you the dimention of the array

built in function to create array

In [10]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#add stepsize
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [13]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [14]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [15]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [16]:
#create evenly spaced numper within a spacified range
#(start,finish,stepsize)
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [17]:
#identity metrix - takes single num bc it must be sq
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

##### Random Numbers

In [18]:
#arrays of random number - 
#generates random samples from uniformly distributed number between 0 and 1
#one dimentional
np.random.rand(5)

array([ 0.50222574,  0.19392963,  0.21216216,  0.56198533,  0.82722873])

In [19]:
#2d random numbers generates - not a tuple
np.random.rand(5,5)

array([[ 0.21665396,  0.86932314,  0.70237291,  0.42641649,  0.68491122],
       [ 0.07899978,  0.50613628,  0.31798761,  0.74394264,  0.17006686],
       [ 0.07105367,  0.75201989,  0.48965697,  0.0825475 ,  0.93483016],
       [ 0.6831581 ,  0.43670453,  0.04434463,  0.73794148,  0.79562029],
       [ 0.69791028,  0.68529051,  0.71895595,  0.71025711,  0.13107413]])

In [20]:
#does not generates random samples from uniformly distributed number 
#but from normal distribution (or gaussian distribution) btw -1 and 1
np.random.randn(2)

array([-0.18859673, -0.74996201])

In [22]:
np.random.randn(4,4)

array([[ 0.47782434,  0.00470876,  1.00585552, -1.0229609 ],
       [-0.7448715 ,  1.22616693,  1.11904095, -0.70615047],
       [-0.51421756,  0.56337593,  0.87597319, -1.1416576 ],
       [ 1.03283522, -0.1579875 , -0.54515461, -0.18828662]])

In [23]:
#[inclusive,exclusive)
np.random.randint(1,10)

1

In [24]:
np.random.randint(1,100,5)

array([70, 66, 53, 42, 95])

###### Array

In [25]:
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
arr2 = np.random.randint(50,300,25)
arr2

array([144, 226, 111,  89, 122, 204, 124, 234, 106, 156,  60, 258, 280,
       218, 100, 166, 295, 145, 171, 185, 143, 144, 261, 279, 256])

In [27]:
#change dimention of an array
arr2.reshape(5,5) #5*5=25

array([[144, 226, 111,  89, 122],
       [204, 124, 234, 106, 156],
       [ 60, 258, 280, 218, 100],
       [166, 295, 145, 171, 185],
       [143, 144, 261, 279, 256]])

In [28]:
arr2

array([144, 226, 111,  89, 122, 204, 124, 234, 106, 156,  60, 258, 280,
       218, 100, 166, 295, 145, 171, 185, 143, 144, 261, 279, 256])

In [30]:
arr2.max()

295

In [31]:
#get position of max == index+1 value
arr2.argmax()

16

In [32]:
arr2.shape

(25,)

In [33]:
new_arr2 = arr2.reshape(5,5)
new_arr2.shape

(5, 5)

In [36]:
new_arr2.dtype

dtype('int32')

In [37]:
#Tip
from numpy.random import randint

randint(2,10,3) #instead of np.random.randint

array([5, 4, 9])

##### Indexing and selection

In [39]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
#get value from a single index
arr[8]

8

In [41]:
#like strings
arr[1:5]

array([1, 2, 3, 4])

In [42]:
arr[8:]

array([ 8,  9, 10])

In [43]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
#its not a copy - it's only a view of the array
slice_of_arr = arr[2:7]
slice_of_arr

array([100, 100, 100,   5,   6])

In [51]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [52]:
#It changes the original array - be very careful
arr

array([100, 100,  99,  99,  99,  99,  99,   7,   8,   9,  10])

In [53]:
#To actually copy
arr_copy = arr.copy()

In [54]:
arr_copy[1:4] = 1
arr_copy

array([100,   1,   1,   1,  99,  99,  99,   7,   8,   9,  10])

In [55]:
#didn't change the original
arr

array([100, 100,  99,  99,  99,  99,  99,   7,   8,   9,  10])

###### indexing 2D arrays

In [56]:
arr_2d = np.array([[3,4,7], [11,22,33], [56,6,78]])
arr_2d

array([[ 3,  4,  7],
       [11, 22, 33],
       [56,  6, 78]])

In [66]:
#grabbing element from 2d array - method 1
arr_2d[0][0]

3

In [65]:
arr_2d[2][1]

6

In [59]:
arr_2d[0]

array([3, 4, 7])

In [67]:
#grabbing element from 2d array - method 2
arr_2d[0,0]

3

In [69]:
arr_2d[2,1]

6

In [70]:
#grab subsection of a metrix
arr_2d[:2,1:]

array([[ 4,  7],
       [22, 33]])

In [72]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
bool_arr = arr >5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [74]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [75]:
#do that in one step
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [76]:
#You can join methods
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

###### Numpy Operations

In [84]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [86]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [87]:
#scaler
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [88]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [89]:
#python error
1/0

ZeroDivisionError: division by zero

In [90]:
#no error, just warning
arr/0

C:\Users\zafri\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':
C:\Users\zafri\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


array([ nan,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf])

In [91]:
1/arr

C:\Users\zafri\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [92]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [93]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [94]:
np.max(arr)

10

In [95]:
arr.max()

10

In [96]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

universal functions (ufunc) - lists all available operations