1. less memory
2. Fast
3. Convinient

Source: numpy tutorial series by codebasics
https://www.youtube.com/watch?v=rN0TREj8G7U&list=PLeo1K3hjS3uset9zIVzJWqplaWBiacTEU

In [1]:
import numpy as np
import time
import sys

In [7]:
l = range(1000)
print('Size of one element:', sys.getsizeof(3)*len(l))

Size of one element: 28000


In [9]:
array = np.arange(1000)
print('Size of one element:', array.size*array.itemsize)

Size of one element: 8000


## Measuring time for computation

In [19]:
SIZE = 1000000
L1 = range(SIZE)
L2 = range(SIZE)

A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

In [20]:
start = time.time()
[x+y for x,y in zip(L1,L2)]
(time.time() - start) * 1000

121.86908721923828

In [21]:
start = time.time()
A1 + A2
(time.time() - start) * 1000

9.629011154174805

In [22]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

In [23]:
a1+a2

array([5, 7, 9])

In [24]:
a1-a2

array([-3, -3, -3])

In [25]:
a1*3

array([3, 6, 9])

In [26]:
a1*a2

array([ 4, 10, 18])

In [27]:
a1/a2

array([ 0.25,  0.4 ,  0.5 ])

In [29]:
a1[0]

1

In [30]:
a1[1]

2

In [31]:
a1.ndim

1

## 2D array

In [32]:
a = np.array([[1,2], [3,4], [5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
a.ndim

2

In [34]:
a[0]

array([1, 2])

In [35]:
a[0][0]

1

In [36]:
a[0][1]

2

In [37]:
# should return 4??
a.dtype

dtype('int64')

In [38]:
a.itemsize

8

In [39]:
b = np.array([[1,2], [3,4], [5,6]], dtype=np.float64)

In [40]:
b.itemsize

8

In [41]:
b.dtype

dtype('float64')

In [42]:
b.size

6

In [43]:
b.shape

(3, 2)

In [44]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [45]:
np.ones( (3,4) )

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [46]:
np.arange(1,5)

array([1, 2, 3, 4])

In [47]:
np.arange(1,5,2)

array([1, 3])

In [48]:
np.linspace(1,5,10)

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

In [50]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [49]:
a.shape

(3, 2)

In [51]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [53]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

## Mathmatics

In [55]:
a.min()

1

In [56]:
a.max()

6

In [57]:
a.sum()

21

In [58]:
# sums the cols
a.sum(axis=0)

array([ 9, 12])

In [59]:
# sums the rows
a.sum(axis=1)

array([ 3,  7, 11])

In [60]:
np.sqrt(a)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ],
       [ 2.23606798,  2.44948974]])

In [61]:
np.std(a)

1.707825127659933

In [63]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [68]:
b = np.array([[2,3], [4,5], [0,9]])

In [69]:
a+b

array([[ 3,  5],
       [ 7,  9],
       [ 5, 15]])

In [70]:
# matrix product
a.dot(b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [74]:
for row in np.array([['__','__','__'], ['__','__','__'], ['__','__','__']]):
    print(row)

['__' '__' '__']
['__' '__' '__']
['__' '__' '__']


## Indexing and Slicing

In [75]:
n = [6,7,8]

In [76]:
n[0:2]

[6, 7]

In [77]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
a[0]

array([1, 2])

In [80]:
a[0:2]

array([[1, 2],
       [3, 4]])

In [82]:
a[0:2,0]

array([1, 3])

In [83]:
a[0:2,1]

array([2, 4])

In [84]:
a[0:3,1]

array([2, 4, 6])

In [85]:
a[-1]

array([5, 6])

In [86]:
a[-1,0:2]

array([5, 6])

In [87]:
a[-1,0:1]

array([5])

## Itterating through Arrays

In [88]:
for row in a:
    print(row)

[1 2]
[3 4]
[5 6]


In [89]:
for cell in a.flat:
    print(cell, end=' ')

1 2 3 4 5 6 

## Stacking together 2 arrays

In [90]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [91]:
b

array([[2, 3],
       [4, 5],
       [0, 9]])

In [92]:
np.vstack( (a,b) )

array([[1, 2],
       [3, 4],
       [5, 6],
       [2, 3],
       [4, 5],
       [0, 9]])

In [94]:
np.hstack( (a,b) )

array([[1, 2, 2, 3],
       [3, 4, 4, 5],
       [5, 6, 0, 9]])

In [96]:
c = np.arange(30).reshape(2,15)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [97]:
np.hsplit(c,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [98]:
hc = np.hsplit(c,3)

In [99]:
for r in hc:
    print(r)

[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [101]:
vc = np.vsplit(c,2)
vc

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

## Indexing with boolean arrays

In [102]:
a= np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [104]:
# it loos at the b array and return only the true value
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [105]:
a[b] = -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

## Irreration

In [108]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [110]:
for row in a:
    print(row)

[0 1 2 3]
[ 4 -1 -1 -1]
[-1 -1 -1 -1]


In [111]:
for row in a:
    for cell in row:
        print(cell, end=' ')

0 1 2 3 4 -1 -1 -1 -1 -1 -1 -1 

In [114]:
for cell in a.flatten():
    print(cell, end=' ')

0 1 2 3 4 -1 -1 -1 -1 -1 -1 -1 

In [115]:
# nditer

In [121]:
for x in np.nditer(a,order='C'):
    print(x, end=' ')

0 1 2 3 4 -1 -1 -1 -1 -1 -1 -1 

In [122]:
for x in np.nditer(a,order='F'):
    print(x, end=' ')

0 4 -1 1 -1 -1 2 -1 -1 3 -1 -1 

In [125]:
# flip rows and coloms
for x in np.nditer(a,order='F', flags=['external_loop']):
    print(x)

[ 0  4 -1]
[ 1 -1 -1]
[ 2 -1 -1]
[ 3 -1 -1]


In [128]:
# changes all elements of an array by the factors provided
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [129]:
a

array([[ 0,  1,  4,  9],
       [16,  1,  1,  1],
       [ 1,  1,  1,  1]])

## itterate through 2 arrays

In [130]:
b = np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [131]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
1 7
1 7
1 7
1 11
1 11
1 11
1 11


for that to work the sixe has to be the same or one has to be one.

In [3]:
a =np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
a2 = a % 3 == 0
a2

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False, False,  True, False],
       [False,  True, False, False,  True]], dtype=bool)

In [6]:
a[a2]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [8]:
x = 56.98
print(type(x))

<class 'float'>


In [10]:
a.sum(axis =0)

array([50, 55, 60, 65, 70])

In [15]:
a.sum(axis =1)

array([ 10,  35,  60,  85, 110])

In [11]:
a.sum(axis = -1)

array([ 10,  35,  60,  85, 110])

In [14]:
a.sum(axis = -2)

array([50, 55, 60, 65, 70])